### PR TITLE
feat(filters): adding _missing_ filter on nested properties

### PR DESCRIPTION
**Pull request by Kapcash**
The "Undefined" filter on table isn't available for nested properties.
I added the support to it using a must_not query filter on ES as a workaround.

Now, only for nested properties and the "missing" operator, we create a "not" filter, behaving as the query_string filter "_missing_". I used the existing error thrown to match only this case and to avoid side effects.

### CODE REVIEW

**Comment by sebaplaza** [comment]
It is my idea or the changes are being made in the dist/ folder , not in the source code ?

**Comment by sebaplaza** [comment]
mm, let me test locally before...
if we consider your modifications, there is a lot of changes in dist/

i'll check that.

**Comment by sebaplaza** [comment]
Well.. after testing..

I checkout the code in commit 7c980e0c

If i add your code to filters.js :
image

The only lines modified in dist/ are : 
image

I think some of your modifications has been made in the dist/ folder.

Can you make another branch and only add your changes, do not commit dist/ files for the moment.

**Comment by sebaplaza** [comment]
I just tested this and i have a different behaviour, for me function() (line 580) is not being deleted.

We can merge and i'm gonna regenerate the dist/ folder.

Please, remove dist/ from .gitignore

**Comment by Kapcash** [comment]
Sure, I've just noticed it as well, this was a mistake.
Just pushed!

**Pull request merged**
